# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aetherium_ml.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'aetherium_ml.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61\x65therium_ml.proto\x12\x0c\x61\x65therium_ml\"<\n\x11\x45mbedBatchRequest\x12\'\n\x06\x63hunks\x18\x01 \x03(\x0b\x32\x17.aetherium_ml.TextChunk\"P\n\tTextChunk\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\x12\x0e\n\x06\x64oc_id\x18\x02 \x01(\t\x12\x13\n\x0b\x63hunk_index\x18\x03 \x01(\x05\x12\x0c\n\x04text\x18\x04 \x01(\t\"F\n\x12\x45mbedBatchResponse\x12\x30\n\nembeddings\x18\x01 \x03(\x0b\x32\x1c.aetherium_ml.ChunkEmbedding\"B\n\x0e\x43hunkEmbedding\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\x12\x0e\n\x06\x64oc_id\x18\x02 \x01(\t\x12\x0e\n\x06vector\x18\x03 \x03(\x02\"\"\n\x11\x45mbedQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\"$\n\x12\x45mbedQueryResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\"\x0f\n\rHealthRequest\"N\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x0c\n\x04\x64ims\x18\x04 \x01(\r2\xfb\x01\n\x12\x41\x65theriumMLService\x12O\n\nEmbedBatch\x12\x1f.aetherium_ml.EmbedBatchRequest\x1a .aetherium_ml.EmbedBatchResponse\x12O\n\nEmbedQuery\x12\x1f.aetherium_ml.EmbedQueryRequest\x1a .aetherium_ml.EmbedQueryResponse\x12\x43\n\x06Health\x12\x1b.aetherium_ml.HealthRequest\x1a\x1c.aetherium_ml.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aetherium_ml_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDBATCHREQUEST']._serialized_start=36
  _globals['_EMBEDBATCHREQUEST']._serialized_end=96
  _globals['_TEXTCHUNK']._serialized_start=98
  _globals['_TEXTCHUNK']._serialized_end=178
  _globals['_EMBEDBATCHRESPONSE']._serialized_start=180
  _globals['_EMBEDBATCHRESPONSE']._serialized_end=250
  _globals['_CHUNKEMBEDDING']._serialized_start=252
  _globals['_CHUNKEMBEDDING']._serialized_end=318
  _globals['_EMBEDQUERYREQUEST']._serialized_start=320
  _globals['_EMBEDQUERYREQUEST']._serialized_end=354
  _globals['_EMBEDQUERYRESPONSE']._serialized_start=356
  _globals['_EMBEDQUERYRESPONSE']._serialized_end=392
  _globals['_HEALTHREQUEST']._serialized_start=394
  _globals['_HEALTHREQUEST']._serialized_end=409
  _globals['_HEALTHRESPONSE']._serialized_start=411
  _globals['_HEALTHRESPONSE']._serialized_end=489
  _globals['_AETHERIUMMLSERVICE']._serialized_start=492
  _globals['_AETHERIUMMLSERVICE']._serialized_end=743
# @@protoc_insertion_point(module_scope)
