# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import aetherium_ml_pb2 as aetherium__ml__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in aetherium_ml_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AetheriumMLServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EmbedBatch = channel.unary_unary(
                '/aetherium_ml.AetheriumMLService/EmbedBatch',
                request_serializer=aetherium__ml__pb2.EmbedBatchRequest.SerializeToString,
                response_deserializer=aetherium__ml__pb2.EmbedBatchResponse.FromString,
                _registered_method=True)
        self.EmbedQuery = channel.unary_unary(
                '/aetherium_ml.AetheriumMLService/EmbedQuery',
                request_serializer=aetherium__ml__pb2.EmbedQueryRequest.SerializeToString,
                response_deserializer=aetherium__ml__pb2.EmbedQueryResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/aetherium_ml.AetheriumMLService/Health',
                request_serializer=aetherium__ml__pb2.HealthRequest.SerializeToString,
                response_deserializer=aetherium__ml__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Cluster = channel.unary_unary(
                '/aetherium_ml.AetheriumMLService/Cluster',
                request_serializer=aetherium__ml__pb2.ClusterRequest.SerializeToString,
                response_deserializer=aetherium__ml__pb2.ClusterResponse.FromString,
                _registered_method=True)


class AetheriumMLServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EmbedBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AetheriumMLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EmbedBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedBatch,
                    request_deserializer=aetherium__ml__pb2.EmbedBatchRequest.FromString,
                    response_serializer=aetherium__ml__pb2.EmbedBatchResponse.SerializeToString,
            ),
            'EmbedQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedQuery,
                    request_deserializer=aetherium__ml__pb2.EmbedQueryRequest.FromString,
                    response_serializer=aetherium__ml__pb2.EmbedQueryResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=aetherium__ml__pb2.HealthRequest.FromString,
                    response_serializer=aetherium__ml__pb2.HealthResponse.SerializeToString,
            ),
            'Cluster': grpc.unary_unary_rpc_method_handler(
                    servicer.Cluster,
                    request_deserializer=aetherium__ml__pb2.ClusterRequest.FromString,
                    response_serializer=aetherium__ml__pb2.ClusterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aetherium_ml.AetheriumMLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aetherium_ml.AetheriumMLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AetheriumMLService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EmbedBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aetherium_ml.AetheriumMLService/EmbedBatch',
            aetherium__ml__pb2.EmbedBatchRequest.SerializeToString,
            aetherium__ml__pb2.EmbedBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aetherium_ml.AetheriumMLService/EmbedQuery',
            aetherium__ml__pb2.EmbedQueryRequest.SerializeToString,
            aetherium__ml__pb2.EmbedQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aetherium_ml.AetheriumMLService/Health',
            aetherium__ml__pb2.HealthRequest.SerializeToString,
            aetherium__ml__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aetherium_ml.AetheriumMLService/Cluster',
            aetherium__ml__pb2.ClusterRequest.SerializeToString,
            aetherium__ml__pb2.ClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
