[package]
name = "aetherium-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
aetherium-core = { path = "../core"}
tokio = { version = "1", features = ["full"]}
tonic = "0.12"
prost = "0.13"
uuid = { version = "1.6", features = ["v4", "fast-rng"] }
toml = "0.5.8"
serde = { version = "1.0.136", features = ["derive"] }
aetherium-macros = {path = "../aetherium-macros"}

[build-dependencies]
tonic-build = "0.12"
